#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

cleanup() {
	rm -f /var/run/docker-pidwatch.pid
}
trap cleanup EXIT
echo $$ > /var/run/docker-pidwatch.pid

log_info() {
	echo "$(date -Iseconds) [INFO] $1"
}
log_error() {
	echo "$(date -Iseconds) [ERROR] $1"
}

RUNDIR=/var/run/docker-pidwatch

log_info "Starting docker-pidwatch"

mkdir -p "$RUNDIR"
cd "$RUNDIR"

while true; do
	log_info "Updating pid files"
	for name in $(docker ps -a --format '{{.Names}}'); do
		pid="$(docker inspect -f '{{.State.Pid}}' "$name" 2>/dev/null || echo 0)"
		if [[ "$pid" -ne 0 ]]; then
			(echo "$pid" > "${name}.pid") || log_error "Failed to create ${RUNDIR}/${name}.pid"
		else
			rm -f "${name}.pid" || log_error "Failed to remove ${RUNDIR}/${name}.pid"
		fi
	done
	sleep 10
done
